name: CD Pipeline
# Only trigger when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: codespace-01
    steps:
      - name: Pull Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: sudo docker pull $DOCKER_USER/bikeshare_model_api:latest
      
      - name: Delete Old Docker Container
        run: sudo docker rm -f bikeshare_model_api-container || true
      
      - name: Run Docker Container
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: sudo docker run -it -d -p 8000:8000 --name bikeshare_model_api-container $DOCKER_USER/bikeshare_model_api:latest
